netname: MyNet

ipconfig:  
  -
    name: ğŸ  home
    ip: 192.168.1.1
    subnetMask: 255.255.255.0
    defaultGateway: 192.168.1.1
    dns: 8.8.8.8
  -
    name: ğŸˆ company
    ip: 192.168.1.10
    subnetMask: 255.255.255.0
    defaultGateway: 192.168.1.1
    dns: 8.8.8.8

  


